### ISSUE TITLE
RuntimeError: can't query kernel attributes

### ISSUE THREAD

**Issue by rashidrafeek** [NVIDIA/cuEquivariance#29]
I installed mace via the instructions provided [here](https://mace-docs.readthedocs.io/en/latest/guide/cuda_acceleration.html). But when I tried to run the following a minimal example:
```
from mace.calculators import mace_mp
from ase import build

# macemp = mace_mp(device="cuda")  # Return ASE calculator
macemp = mace_mp(device="cuda", enable_cueq=True)  # Return ASE calculator
atoms = build.molecule('H2O')
descriptors_mp = macemp.get_descriptors(atoms)
```
I got an error `RuntimeError: can't query kernel attributes`. I am creating the issue here as it seemed the error originated from this library. The full error is:
<details>
<summary>Click to expand error</summary>

```python
Traceback (most recent call last):
  File "/home/rashid/Misc/mace/01_gpu_descriptor.py", line 7, in <module>
    descriptors_mp = macemp.get_descriptors(atoms)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/mace/calculators/mace.py", line 407, in get_descriptors
    descriptors = [model(batch.to_dict())["node_feats"] for model in self.models]
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/mace/modules/models.py", line 412, in forward
    node_feats, sc = interaction(
                     ^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/mace/modules/blocks.py", line 751, in forward
    mji = self.conv_tp(
          ^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/mace/modules/wrapper_ops.py", line 157, in cuet_forward
    return self.original_forward(x, y, z, use_fallback=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_torch/operations/tp_channel_wise.py", line 150, in forward
    return self.f(weight, x1, x2, use_fallback=use_fallback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_torch/primitives/equivariant_tensor_product.py", line 168, in forward
    output = self.tp(*inputs, use_fallback=use_fallback)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_torch/primitives/tensor_product.py", line 97, in forward
    return self.f_cuda(*args)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_torch/primitives/tensor_product.py", line 625, in forward
    out = self._f(x0, x1, x2)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_ops_torch/tensor_product_uniform_1d.py", line 573, in forward
    out = tensor_product_uniform_1d_fwd(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_ops_torch/tensor_product_uniform_1d.py", line 339, in tensor_product_uniform_1d_fwd
    return torch.ops.cuequivariance_ops_torch.tensor_product_uniform_4x1d_fwd_primitive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/_ops.py", line 1116, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/_library/autograd.py", line 111, in autograd_impl
    result = Generated.apply(*args, Metadata(keyset, keyword_only_args))  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/_library/autograd.py", line 50, in forward
    result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/torch/_ops.py", line 721, in redispatch
    return self._handle.redispatch_boxed(keyset, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_ops_torch/tensor_product_uniform_1d.py", line 228, in _
    return _fwd_impl(
           ^^^^^^^^^^
  File "/home/rashid/Apps/mambaforge/envs/mace/lib/python3.12/site-packages/cuequivariance_ops_torch/tensor_product_uniform_1d.py", line 45, in _fwd_impl
    ext.tensor_product_uniform_1d_fwd(
RuntimeError: can't query kernel attributes
```
</details> 

GPU details:
Device name: NVIDIA GeForce GTX 1070 Ti
CUDA Version: 11.8

Any suggestions on fixing this be helpful. Thanks.

**Comment by v0i0** [comment]
Hey, @rashidrafeek. We do not support Pascal-generation GPU's currently, so this is expected. If you use Volta or up, this will work.

**Comment by rashidrafeek** [comment]
Thanks.
