### ISSUE TITLE
Question about (batch, irreps_dim) inputs with `cue.ir_mul`

### ISSUE THREAD

**Issue by mitkotak** [NVIDIA/cuEquivariance#31]
Was a bit confused by [this](https://github.com/NVIDIA/cuEquivariance/blob/04595a85741784878c8c39de6b6a811354aef24f/cuequivariance_torch/cuequivariance_torch/primitives/equivariant_tensor_product.py#L148-L154) behavior since I thought `cue.ir_mul` would expect inputs of shape (irreps_dim, batch) unless I am missing something. Thanks !

```python
>>> import cuequivariance_torch as cuet
>>> import cuequivariance as cue
>>> e = cue.descriptors.fully_connected_tensor_product(cue.Irreps("O3", "32x0e + 32x1o"),
...                                                    cue.Irreps("O3", "0e + 1o"),
...                                                    cue.Irreps("O3", "32x0e + 32x1o"))
>>> m = cuet.EquivariantTensorProduct(e, layout=cue.ir_mul)
>>> import torch
>>> input1 = torch.randn(100, e.inputs[1].irreps.dim)
>>> input2 = torch.randn(100, e.inputs[2].irreps.dim)
>>> w = torch.randn(e.inputs[0].irreps.dim)
>>> m(w, input1, input2)
/home/mkotak/.local/lib/python3.10/site-packages/cuequivariance_torch/primitives/tensor_product.py:106: UserWarning: The fallback method is used but it has not been optimized. Consider setting optimize_fallback=True when creating the TensorProduct module.
  warnings.warn(
tensor([[-1.6332,  1.4711, -1.9731,  ...,  0.1358, -0.5038, -0.5826],
        [-1.0257, -0.3940,  0.6957,  ..., -0.6269, -0.0165,  0.4533],
        [ 0.1508, -0.8899,  0.3030,  ..., -0.9799, -0.8084, -0.4569],
        ...,
        [ 1.0862, -0.0096,  5.3136,  ...,  0.4343, -0.4275, -0.3927],
        [ 0.1382,  0.6793, -0.7609,  ..., -0.0320,  0.0103, -0.0777],
        [-1.7030,  0.9429, -1.1852,  ..., -0.2984,  0.7450, -0.0921]])
>>> m(w, input1.T, input2.T)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mkotak/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mkotak/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mkotak/.local/lib/python3.10/site-packages/cuequivariance_torch/primitives/equivariant_tensor_product.py", line 153, in forward
    assert a.shape[-1] == b.irreps.dim
AssertionError
```

**Comment by moradza** [comment]
mul_ir and ir_mul only change the data arrangement within dim[-1] of irreps tensors. You should use `TransposeSegments, TransposeIrrepsLayout` to change layouts, not torch built-in transpose. An example below,
```
irps = cue.Irreps("O3", "3x1o")
# both tensors refer to the same input with two different layouts
x_mul_ir = torch.tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])
x_ir_mul = torch.tensor([[0, 3, 6, 1, 4, 7, 2, 5, 8]])
```

**Comment by mitkotak** [comment]
Gotcha. Thanks !

is there a way to control whether the transposes happen or not inside `EquivariantTensorProduct` (so that I can do them externally before calling cuet) cause currently seems like its always doing the inputs and output transposes.

**Comment by mitkotak** [comment]
Also can you help me figure out what I might be doing wrong here

```python
import cuequivariance as cue
import cuequivariance_torch as cuet
import torch

e = cue.descriptors.fully_connected_tensor_product(
    cue.Irreps("O3", "2x1e"),
    cue.Irreps("O3", "2x1e"),
    cue.Irreps("O3", "2x1e"))

m = cuet.EquivariantTensorProduct(e, layout=cue.ir_mul)

w = torch.randn(e.inputs[0].irreps.dim)
input1_mul_ir = torch.randn(1, e.inputs[1].irreps.dim)
input2_mul_ir = torch.randn(1, e.inputs[2].irreps.dim)

result = m(w, input1_mul_ir, input2_mul_ir)

input1_ir_mul = cuet.primitives.transpose.TransposeIrrepsLayout(
    e.inputs[1].irreps,
    source = cue.mul_ir,
    target = cue.ir_mul
)(input1_mul_ir)

input2_ir_mul = cuet.primitives.transpose.TransposeIrrepsLayout(
    e.inputs[2].irreps,
    source = cue.mul_ir,
    target = cue.ir_mul
)(input2_mul_ir)


result_ir_mul = m(w, input1_ir_mul, input2_ir_mul)

result_mul_ir = cuet.primitives.transpose.TransposeIrrepsLayout(
    e.output.irreps,
    source = cue.ir_mul,
    target = cue.mul_ir
)(result_ir_mul)


torch.testing.assert_close(result, result_mul_ir) # Fails
```

**Comment by moradza** [comment]
The module formulates tensor product based on the layout you give to it, so you need to define another module with corresponding layout. 

```
import cuequivariance as cue
import cuequivariance_torch as cuet
import torch

e = cue.descriptors.fully_connected_tensor_product(
    cue.Irreps("O3", "2x1e"),
    cue.Irreps("O3", "2x1e"),
    cue.Irreps("O3", "2x1e"))

m_mul_ir = cuet.EquivariantTensorProduct(e, layout=cue.mul_ir)

w = torch.randn(e.inputs[0].irreps.dim)
input1_mul_ir = torch.randn(1, e.inputs[1].irreps.dim)
input2_mul_ir = torch.randn(1, e.inputs[2].irreps.dim)

result = m_mul_ir(w, input1_mul_ir, input2_mul_ir)

input1_ir_mul = cuet.primitives.transpose.TransposeIrrepsLayout(
    e.inputs[1].irreps,
    source=cue.mul_ir,
    target=cue.ir_mul
)(input1_mul_ir)

input2_ir_mul = cuet.primitives.transpose.TransposeIrrepsLayout(
    e.inputs[2].irreps,
    source=cue.mul_ir,
    target=cue.ir_mul
)(input2_mul_ir)


m_ir_mul = cuet.EquivariantTensorProduct(e, layout=cue.ir_mul)

result_ir_mul = m_ir_mul(w, input1_ir_mul, input2_ir_mul)

result_mul_ir = cuet.primitives.transpose.TransposeIrrepsLayout(
    e.output.irreps,
    source=cue.ir_mul,
    target=cue.mul_ir
)(result_ir_mul)


torch.testing.assert_close(result, result_mul_ir)  # Fails

```

**Comment by moradza** [comment]
> Gotcha. Thanks !
> 
> is there a way to control whether the transposes happen or not inside `EquivariantTensorProduct` (so that I can do them externally before calling cuet) cause currently seems like its always doing the inputs and output transposes.

Not sure if I get your question, but try using ir_mul layout, it should avoid use of transpose.

**Comment by mitkotak** [comment]
Sorry the context is that I setup a simple tetris model [here](https://github.com/atomicarchitects/e3nn_tetris/pull/6/files#diff-c0ea845a0eabcd0b8c56d746bb661120782ffea774cbebc42c25843468c68a4d) and was wondering whether it only transposes once (I use ir_mul everywhere) or whether it does it repeatedly.

**Comment by moradza** [comment]
As long as your inputs have the same layout as layout used to build the model, it will not transpose the irreps. In this case, the transpose will be `identity` which is supposed to be no-op.
