### ISSUE TITLE
Cannot install from source, missing LICENSE file

### ISSUE THREAD

**Issue by fxcoudert** [NVIDIA/cuEquivariance#53]
Installing from source with `pip install ./cuequivariance-0.1.0 -vv --no-deps --no-build-isolation` from the file at https://files.pythonhosted.org/packages/ec/bf/146e021113f2aedd54868ab98d0d5e0c47702a01bc1c1803c5bec309ece6/cuequivariance-0.1.0.tar.gz

fails because license files are not distributed. 

```
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
      ~~~~^^
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/hatchling/build.py", line 58, in build_wheel
      return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                              ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
      self.metadata.validate_fields()
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/hatchling/metadata/core.py", line 266, in validate_fields
      self.core.validate_fields()
      ~~~~~~~~~~~~~~~~~~~~~~~~~^^
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/hatchling/metadata/core.py", line 1366, in validate_fields
      getattr(self, attribute)
      ~~~~~~~^^^^^^^^^^^^^^^^^
    File "/Users/fx/miniforge3/envs/test/lib/python3.13/site-packages/hatchling/metadata/core.py", line 700, in license
      raise OSError(message)
  OSError: License file does not exist: ../LICENSES/LICENSE
  error: subprocess-exited-with-error
```

**Comment by mariogeiger** [comment]
Hi,

Do you think this would fix you issue? https://github.com/NVIDIA/cuEquivariance/pull/56

**Comment by mariogeiger** [comment]
Should be fixed by #56 in next release. Please re-open in case there is still a problem.
